theme: jekyll-theme-slate
title: mickp.github.io
defaults:
 - scope:
     path: "ConwayToneMatrix"
   values:
     title: ConwayToneMatrix
     permalink: "/conway/"
 
 - scope:
     path: "tunes"
   values:
     title: Tunes
     permalink: "/tunes"
     tunesUrl: "/tunes"